# Generated by Django 5.0 on 2024-01-13 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_user_alter_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='userOFwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
