# Generated by Django 5.0 on 2024-01-13 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='current_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='userOFwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
