# Generated by Django 5.0 on 2024-01-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_price_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_bid',
            new_name='price',
        ),
    ]
